name: Deploy to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install AWS CLI
        run: |
          pip install awscli --upgrade --user

      - name: Determine Updated Lambda Function
        id: determine_updated_function
        run: |
          # Use git to find the directory that has been modified
          updated_folder=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/.*\.py$' | sed 's/\/.*\.py$//')
          echo "Updated Lambda Function: $updated_folder"
          echo "::set-output name=updated_folder::$updated_folder"

      - name: Deploy Updated Lambda Function
        if: steps.determine_updated_function.outputs.updated_folder != ''
        run: |
          cd ${{ steps.determine_updated_function.outputs.updated_folder }}
          zip -r lambda-deployment-package.zip .
          aws lambda update-function-code \
            --function-name ${{ steps.determine_updated_function.outputs.updated_folder }} \
            --zip-file fileb://lambda-deployment-package.zip
          cd ../

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
