name: Deploy to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install AWS CLI
        run: |
          pip install awscli --upgrade --user

      - name: Determine Updated Lambda Function
        id: determine_updated_function
        run: |
          # Use git to find the directory that has been modified
          if [ "$(git rev-parse ${GITHUB_SHA}^2)" = "4b825dc642cb6eb9a060e54bf8d69288fbee4904" ]; then
            # Initial commit, get all directories
            updated_folder=$(ls -d */ | sed 's#/##')
          else
            # Get all directories in the current commit
            all_folders=$(git ls-tree --name-only -r ${GITHUB_SHA} | grep '/.*$' | sed -n 's#^\([^/]\+\)/.*$#\1#p' | sort -u)

            # Get changed directories between the current and previous commit
            changed_folders=$(git diff --name-only ${GITHUB_SHA}^1 $GITHUB_SHA | grep '/.*$' | sed -n 's#^\([^/]\+\)/.*$#\1#p' | sort -u)

            # Find the intersection of all directories and changed directories
            updated_folder=$(comm -12 <(echo "$all_folders") <(echo "$changed_folders"))
          fi

          echo "Updated Lambda Function: $updated_folder"
          echo "updated_folder=$updated_folder" >> $GITHUB_ENV

      - name: Deploy Updated Lambda Function
        if: env.updated_folder != ''
        run: |
          cd ${{ env.updated_folder }}
          zip -r lambda-deployment-package.zip .
          aws lambda update-function-code \
            --function-name ${{ env.updated_folder }} \
            --zip-file fileb://lambda-deployment-package.zip
          cd ../
            
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
