name: Deploy to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install AWS CLI
        run: |
          pip install awscli --upgrade --user

      - name: Determine Updated Lambda Function
        id: determine_updated_function
        run: |
          # Use git to find the directory that has been modified
          if [ -z "${{ github.event.before }}" ]; then
            # Handle the case where github.event.before is empty (initial commit)
            updated_folder=$(ls -d */ | sed 's#/##')
          else
            updated_folder=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | sed -n 's#^\([^/]\+\)/.*$#\1#p' | sort -u)
          fi
          echo "Updated Lambda Function: $updated_folder"
          echo "updated_folder=$updated_folder" >> $GITHUB_ENV

      - name: Deploy Updated Lambda Function
        if: env.updated_folder != ''
        run: |
          cd ${{ env.updated_folder }}
          zip -r lambda-deployment-package.zip .
          aws lambda update-function-code \
            --function-name ${{ env.updated_folder }} \
            --zip-file fileb://lambda-deployment-package.zip
          cd ../

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
